"""Pydantic models for report generation."""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class ReportType(str, Enum):
    CLINICAL_SUMMARY = "clinical_summary"
    EVIDENCE_REVIEW = "evidence_review"


class ReportFormat(str, Enum):
    JSON = "json"
    PDF = "pdf"


class Citation(BaseModel):
    """A single citation reference."""
    index: int
    title: str
    source_type: str
    evidence_level: int = 3
    year: Optional[int] = None
    journal: Optional[str] = None
    doi: Optional[str] = None
    pmid: Optional[str] = None


class SafetyWarning(BaseModel):
    """A safety warning from validation."""
    warning_type: str
    severity: str
    message: str
    matched_text: Optional[str] = None


class ConfidenceBreakdown(BaseModel):
    """Confidence score breakdown."""
    citation_score: float = 0.0
    evidence_score: float = 0.0
    hallucination_score: float = 0.0
    quality_score: float = 0.0
    consistency_score: float = 0.0
    safety_penalty: float = 0.0


class ReportRequest(BaseModel):
    """Request to generate a report."""
    report_type: ReportType = Field(
        default=ReportType.CLINICAL_SUMMARY,
        description="Type of report to generate",
    )
    query: str = Field(..., min_length=1, max_length=500, description="Original clinical query")
    answer: str = Field(..., min_length=1, description="Generated answer text")
    citations: list[Citation] = Field(default_factory=list, description="Source citations")
    safety_warnings: list[SafetyWarning] = Field(default_factory=list)
    confidence_score: float = Field(default=0.0, ge=0.0, le=1.0)
    confidence_breakdown: Optional[ConfidenceBreakdown] = None
    recommendation: str = Field(default="NEEDS_REVIEW")
    source_chunks: list[dict[str, Any]] = Field(default_factory=list)
    format: ReportFormat = Field(default=ReportFormat.JSON)


class ReportMetadata(BaseModel):
    """Report generation metadata."""
    report_id: str
    report_type: str
    generated_at: datetime
    query: str
    confidence_score: float
    recommendation: str
    citation_count: int
    safety_warning_count: int
    format: str


class ClinicalSummaryReport(BaseModel):
    """Structured clinical summary report."""
    metadata: ReportMetadata
    query: str
    clinical_answer: str
    key_findings: list[str] = Field(default_factory=list)
    evidence_summary: str = ""
    citations: list[Citation] = Field(default_factory=list)
    safety_warnings: list[SafetyWarning] = Field(default_factory=list)
    confidence_assessment: str = ""
    recommendation: str = "NEEDS_REVIEW"
    disclaimer: str = (
        "This report is generated by an AI clinical decision support system. "
        "It should not replace clinical judgment. All recommendations should be "
        "verified by a qualified healthcare professional before clinical application."
    )


class EvidenceReviewReport(BaseModel):
    """Detailed evidence review report."""
    metadata: ReportMetadata
    query: str
    answer: str
    evidence_analysis: str = ""
    source_breakdown: dict[str, int] = Field(default_factory=dict)
    evidence_levels: dict[str, int] = Field(default_factory=dict)
    citations: list[Citation] = Field(default_factory=list)
    hallucination_flags: list[dict[str, Any]] = Field(default_factory=list)
    safety_warnings: list[SafetyWarning] = Field(default_factory=list)
    confidence_breakdown: Optional[ConfidenceBreakdown] = None
    quality_notes: str = ""
    disclaimer: str = (
        "This evidence review is generated by an AI system. "
        "Source quality and relevance should be independently verified."
    )
