{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# OpenInsight Data Ingestion Pipeline — Kaggle Edition\n",
    "\n",
    "This notebook runs the full ingestion pipeline on Kaggle's free GPU (T4/T4x2) and stores\n",
    "all data to **Zilliz Cloud** (Milvus) and **MongoDB Atlas**.\n",
    "\n",
    "## Architecture\n",
    "```\n",
    "Kaggle GPU (T4, 16GB VRAM)\n",
    "  └── PDFs (Kaggle Dataset)\n",
    "       ↓\n",
    "  GROBID/OCR → Structured Text\n",
    "       ↓\n",
    "  Dedup → Enrich → Chunk (350 tokens)\n",
    "       ↓\n",
    "  S-PubMedBert (768d dense) ──→ Zilliz Cloud\n",
    "  TF-IDF (sparse, CPU-only)  ──→ Zilliz Cloud\n",
    "       ↓\n",
    "  Metadata ──→ MongoDB Atlas\n",
    "  Checkpoints ──→ /kaggle/working (5GB persistent)\n",
    "```\n",
    "\n",
    "## Setup Instructions\n",
    "1. Upload your medical PDFs as a **Private Kaggle Dataset**\n",
    "2. Enable **Internet** in Settings (required for Zilliz/MongoDB)\n",
    "3. Enable **GPU** accelerator (Settings → Accelerator → GPU T4 x2)\n",
    "4. Fill in the configuration cell below with your credentials\n",
    "5. Run all cells\n",
    "\n",
    "## Quotas\n",
    "- **Kaggle Free**: 30 GPU hours/week, 12hr max session, 100GB private datasets\n",
    "- **Zilliz Cloud Free**: 1 collection, 1M vectors\n",
    "- **MongoDB Atlas Free**: 512MB storage"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Configuration\n",
    "\n",
    "Fill in your credentials below. **Never commit these to a public repo!**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "# ============ REQUIRED: Fill in your credentials ============\n",
    "\n",
    "# Zilliz Cloud (Milvus)\n",
    "ZILLIZ_URI = \"https://in01-xxxx.api.gcp-us-west1.zillizcloud.com\"  # Your Zilliz Cloud endpoint\n",
    "ZILLIZ_TOKEN = \"your_zilliz_api_key\"  # Your Zilliz Cloud API key\n",
    "\n",
    "# MongoDB Atlas\n",
    "MONGODB_URL = \"mongodb+srv://user:password@cluster.mongodb.net/openinsight\"  # Your Atlas connection string\n",
    "MONGODB_DB = \"openinsight\"\n",
    "\n",
    "# NCBI (optional, for PubMed fetching)\n",
    "NCBI_API_KEY = \"\"  # Get free at https://www.ncbi.nlm.nih.gov/account/\n",
    "NCBI_EMAIL = \"your_email@example.com\"\n",
    "\n",
    "# ============ Ingestion Settings ============\n",
    "\n",
    "# Source type: pubmed, icmr, cochrane, who, cdc, statpearls, nmc_guideline, rssdi\n",
    "SOURCE_TYPE = \"pubmed\"\n",
    "\n",
    "# Path to PDFs (Kaggle auto-mounts datasets under /kaggle/input/)\n",
    "DATA_DIR = \"/kaggle/input/your-dataset-name/\"  # Change to your dataset name\n",
    "\n",
    "# Batch size for processing\n",
    "BATCH_SIZE = 10\n",
    "\n",
    "# Set environment variables for the pipeline\n",
    "os.environ[\"EMBED_PROVIDER\"] = \"local\"  # Use local GPU for ingestion\n",
    "os.environ[\"RERANK_PROVIDER\"] = \"local\"  # Use local GPU for reranking\n",
    "os.environ[\"DENSE_MODEL_NAME\"] = \"pritamdeka/S-PubMedBert-MS-MARCO\"\n",
    "os.environ[\"RERANKER_MODEL_NAME\"] = \"BAAI/bge-reranker-v2-m3\"\n",
    "os.environ[\"VECTOR_URI\"] = ZILLIZ_URI\n",
    "os.environ[\"VECTOR_TOKEN\"] = ZILLIZ_TOKEN\n",
    "os.environ[\"MONGODB_URL\"] = MONGODB_URL\n",
    "os.environ[\"MONGODB_DB\"] = MONGODB_DB\n",
    "os.environ[\"NCBI_API_KEY\"] = NCBI_API_KEY\n",
    "os.environ[\"NCBI_EMAIL\"] = NCBI_EMAIL\n",
    "os.environ[\"MILVUS_CLOUD\"] = \"true\"\n",
    "os.environ[\"VECTOR_COLLECTION_V2\"] = \"openinsight_v2\"\n",
    "\n",
    "print(\"Configuration set!\")\n",
    "print(f\"Source type: {SOURCE_TYPE}\")\n",
    "print(f\"Data directory: {DATA_DIR}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Install Dependencies"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Install OpenInsight dependencies\n",
    "!pip install -q sentence-transformers pymilvus pymongo httpx loguru pydantic-settings transformers\n",
    "\n",
    "# Install GROBID dependencies (Java + GROBID server)\n",
    "!apt-get update -qq && apt-get install -qq -y default-jre wget > /dev/null 2>&1\n",
    "\n",
    "# Download and start GROBID server\n",
    "!wget -q https://github.com/grobidOrg/grobid/releases/download/0.9.0/grobid-0.9.0.zip\n",
    "!unzip -q -o grobid-0.9.0.zip -d grobid\n",
    "\n",
    "import subprocess\n",
    "import time\n",
    "\n",
    "# Start GROBID in background\n",
    "grobid_proc = subprocess.Popen(\n",
    "    [\"./grobid/grobid-0.9.0/bin/grobid-server\", \"--port\", \"8070\"],\n",
    "    stdout=subprocess.PIPE,\n",
    "    stderr=subprocess.PIPE,\n",
    ")\n",
    "\n",
    "# Wait for GROBID to start (0.9.0 may take longer due to model loading)\n",
    "print(\"Starting GROBID server (0.9.0)...\")\n",
    "time.sleep(45)\n",
    "\n",
    "# Verify GROBID is running using the new health endpoint (0.9.0+) with fallback\n",
    "import httpx\n",
    "try:\n",
    "    # Try new health endpoint first (GROBID 0.9.0+)\n",
    "    resp = httpx.get(\"http://localhost:8070/api/health\", timeout=15)\n",
    "    print(f\"GROBID server status: {'ALIVE' if resp.status_code == 200 else 'NOT RESPONDING'}\")\n",
    "except Exception as e:\n",
    "    try:\n",
    "        # Fallback to isalive endpoint (GROBID < 0.9.0)\n",
    "        resp = httpx.get(\"http://localhost:8070/api/isalive\", timeout=15)\n",
    "        print(f\"GROBID server status: {'ALIVE' if resp.status_code == 200 else 'NOT RESPONDING'}\")\n",
    "    except Exception as e2:\n",
    "        print(f\"GROBID server may still be starting: {e2}\")\n",
    "\n",
    "os.environ[\"GROBID_URL\"] = \"http://localhost:8070\"\n",
    "\n",
    "# Verify GPU\n",
    "import torch\n",
    "print(f\"\\nGPU available: {torch.cuda.is_available()}\")\n",
    "if torch.cuda.is_available():\n",
    "    print(f\"GPU: {torch.cuda.get_device_name(0)}\")\n",
    "    print(f\"VRAM: {torch.cuda.get_device_properties(0).total_mem / 1e9:.1f} GB\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Clone and Setup OpenInsight"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "\n",
    "# Clone the repo (or upload as a Kaggle dataset for faster access)\n",
    "!git clone -b restruct https://github.com/Adi103-ETAI/openinsight.git /kaggle/working/openinsight\n",
    "\n",
    "# Add to Python path\n",
    "sys.path.insert(0, \"/kaggle/working/openinsight\")\n",
    "\n",
    "print(\"OpenInsight repo cloned and added to path!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Verify Connections\n",
    "\n",
    "Test that Zilliz Cloud and MongoDB Atlas are reachable from Kaggle."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pymilvus import MilvusClient\n",
    "from pymongo import MongoClient\n",
    "\n",
    "# Test Zilliz Cloud connection\n",
    "try:\n",
    "    zilliz_client = MilvusClient(uri=ZILLIZ_URI, token=ZILLIZ_TOKEN)\n",
    "    collections = zilliz_client.list_collections()\n",
    "    print(f\"Zilliz Cloud: Connected! Existing collections: {collections}\")\n",
    "except Exception as e:\n",
    "    print(f\"Zilliz Cloud: FAILED - {e}\")\n",
    "    print(\"Check your VECTOR_URI and VECTOR_TOKEN\")\n",
    "\n",
    "# Test MongoDB Atlas connection\n",
    "try:\n",
    "    mongo_client = MongoClient(MONGODB_URL, serverSelectionTimeoutMS=5000)\n",
    "    mongo_client.server_info()  # Forces connection test\n",
    "    print(f\"MongoDB Atlas: Connected! Database: {MONGODB_DB}\")\n",
    "except Exception as e:\n",
    "    print(f\"MongoDB Atlas: FAILED - {e}\")\n",
    "    print(\"Check your MONGODB_URL\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Run Ingestion Pipeline\n",
    "\n",
    "This is the main ingestion step. It will:\n",
    "1. Parse all PDFs/XMLs in the data directory\n",
    "2. Deduplicate documents\n",
    "3. Enrich metadata\n",
    "4. Chunk into 350-token segments\n",
    "5. Quality score and filter\n",
    "6. Generate dense embeddings (S-PubMedBert, 768d) using GPU\n",
    "7. Generate sparse vectors (TF-IDF, CPU-only)\n",
    "8. Upsert to Zilliz Cloud\n",
    "9. Store documents and chunks to MongoDB Atlas\n",
    "10. Save checkpoints for resumability"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import asyncio\n",
    "from src.ingestion.pipeline import IngestionPipeline\n",
    "\n",
    "async def run_ingestion():\n",
    "    pipeline = IngestionPipeline()\n",
    "    \n",
    "    print(f\"Starting ingestion for source: {SOURCE_TYPE}\")\n",
    "    print(f\"Data directory: {DATA_DIR}\")\n",
    "    print(f\"Batch size: {BATCH_SIZE}\")\n",
    "    print(\"=\" * 50)\n",
    "    \n",
    "    summary = await pipeline.ingest_directory(\n",
    "        directory=DATA_DIR,\n",
    "        source=SOURCE_TYPE,\n",
    "        recreate_index=False,  # Set True to recreate collection\n",
    "        batch_size=BATCH_SIZE,\n",
    "        resume=True,  # Resume from checkpoint if interrupted\n",
    "        reset=False,  # Set True to start fresh\n",
    "    )\n",
    "    \n",
    "    print(\"\\n\" + \"=\" * 50)\n",
    "    print(\"INGESTION COMPLETE\")\n",
    "    print(\"=\" * 50)\n",
    "    for key, value in summary.items():\n",
    "        print(f\"  {key}: {value}\")\n",
    "    \n",
    "    return summary\n",
    "\n",
    "# Run the pipeline\n",
    "summary = await run_ingestion()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Verify Ingested Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Verify data in Zilliz Cloud\n",
    "from pymilvus import MilvusClient\n",
    "\n",
    "zilliz_client = MilvusClient(uri=ZILLIZ_URI, token=ZILLIZ_TOKEN)\n",
    "\n",
    "collection_name = os.environ.get(\"VECTOR_COLLECTION_V2\", \"openinsight_v2\")\n",
    "\n",
    "if zilliz_client.has_collection(collection_name):\n",
    "    stats = zilliz_client.get_collection_stats(collection_name)\n",
    "    print(f\"Zilliz Cloud - Collection: {collection_name}\")\n",
    "    print(f\"  Row count: {stats.get('row_count', 'unknown')}\")\n",
    "else:\n",
    "    print(f\"Collection {collection_name} not found!\")\n",
    "\n",
    "# Verify data in MongoDB Atlas\n",
    "from pymongo import MongoClient\n",
    "\n",
    "mongo_client = MongoClient(MONGODB_URL)\n",
    "db = mongo_client[MONGODB_DB]\n",
    "\n",
    "doc_count = db.documents.count_documents({})\n",
    "chunk_count = db.chunks.count_documents({})\n",
    "failed_count = db.failed_documents.count_documents({})\n",
    "\n",
    "print(f\"\\nMongoDB Atlas - Database: {MONGODB_DB}\")\n",
    "print(f\"  Documents: {doc_count}\")\n",
    "print(f\"  Chunks: {chunk_count}\")\n",
    "print(f\"  Failed (dead letter): {failed_count}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Quick Search Test (Optional)\n",
    "\n",
    "Test that the ingested data is searchable with a simple query."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Quick search test\n",
    "from src.ml.embedding.embedder import LocalEmbedder\n",
    "from pymilvus import MilvusClient\n",
    "\n",
    "embedder = LocalEmbedder(\"pritamdeka/S-PubMedBert-MS-MARCO\")\n",
    "zilliz_client = MilvusClient(uri=ZILLIZ_URI, token=ZILLIZ_TOKEN)\n",
    "\n",
    "test_query = \"What are the current guidelines for type 2 diabetes management in India?\"\n",
    "\n",
    "# Embed query\n",
    "query_vector = embedder.embed_query(test_query).tolist()\n",
    "\n",
    "# Search Zilliz Cloud\n",
    "results = zilliz_client.search(\n",
    "    collection_name=collection_name,\n",
    "    data=[query_vector],\n",
    "    anns_field=\"dense\",\n",
    "    limit=5,\n",
    "    output_fields=[\"chunk_id\", \"source\", \"source_type\", \"chunk_type\"],\n",
    ")\n",
    "\n",
    "print(f\"Query: {test_query}\")\n",
    "print(f\"\\nTop 5 results:\")\n",
    "if results and results[0]:\n",
    "    for i, hit in enumerate(results[0]):\n",
    "        entity = hit.get(\"entity\", {})\n",
    "        print(f\"  {i+1}. Score: {hit.get('distance', 0):.4f} | \"\n",
    "              f\"Source: {entity.get('source_type', '?')} | \"\n",
    "              f\"Type: {entity.get('chunk_type', '?')}\")\n",
    "else:\n",
    "    print(\"  No results found. Check your ingestion.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Ingest Multiple Sources\n",
    "\n",
    "Run this cell to ingest from multiple source directories sequentially."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ingest multiple sources\n",
    "# Update paths to match your Kaggle dataset structure\n",
    "\n",
    "SOURCES = {\n",
    "    # \"pubmed\": \"/kaggle/input/your-dataset/pubmed/\",\n",
    "    # \"icmr\": \"/kaggle/input/your-dataset/icmr/\",\n",
    "    # \"who\": \"/kaggle/input/your-dataset/who/\",\n",
    "    # \"cochrane\": \"/kaggle/input/your-dataset/cochrane/\",\n",
    "    # \"cdc\": \"/kaggle/input/your-dataset/cdc/\",\n",
    "    # \"statpearls\": \"/kaggle/input/your-dataset/statpearls/\",\n",
    "}\n",
    "\n",
    "async def ingest_all_sources():\n",
    "    pipeline = IngestionPipeline()\n",
    "    all_summaries = {}\n",
    "    \n",
    "    for source, data_dir in SOURCES.items():\n",
    "        print(f\"\\n{'='*50}\")\n",
    "        print(f\"Ingesting source: {source}\")\n",
    "        print(f\"Directory: {data_dir}\")\n",
    "        print('='*50)\n",
    "        \n",
    "        try:\n",
    "            summary = await pipeline.ingest_directory(\n",
    "                directory=data_dir,\n",
    "                source=source,\n",
    "                batch_size=BATCH_SIZE,\n",
    "                resume=True,\n",
    "            )\n",
    "            all_summaries[source] = summary\n",
    "            print(f\"  Completed: {summary.get('chunks_indexed', 0)} chunks indexed\")\n",
    "        except Exception as e:\n",
    "            print(f\"  FAILED: {e}\")\n",
    "            all_summaries[source] = {\"error\": str(e)}\n",
    "    \n",
    "    return all_summaries\n",
    "\n",
    "# Uncomment to run:\n",
    "# summaries = await ingest_all_sources()\n",
    "# for source, summary in summaries.items():\n",
    "#     print(f\"{source}: {summary}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Save Progress & Cleanup\n",
    "\n",
    "Kaggle auto-saves files in `/kaggle/working/` (up to 5GB). The next time you run\n",
    "this notebook, set `resume=True` to continue from where you left off."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Save ingestion summary to persistent storage\n",
    "import json\n",
    "\n",
    "summary_path = \"/kaggle/working/ingestion_summary.json\"\n",
    "\n",
    "try:\n",
    "    with open(summary_path, \"w\") as f:\n",
    "        json.dump({\"last_run\": summary}, f, indent=2, default=str)\n",
    "    print(f\"Summary saved to {summary_path}\")\n",
    "except Exception as e:\n",
    "    print(f\"Could not save summary: {e}\")\n",
    "\n",
    "# Stop GROBID server\n",
    "try:\n",
    "    grobid_proc.terminate()\n",
    "    print(\"GROBID server stopped.\")\n",
    "except:\n",
    "    pass\n",
    "\n",
    "print(\"\\nDone! Your data is now in Zilliz Cloud and MongoDB Atlas.\")\n",
    "print(\"Connect your query pipeline to these databases to start searching.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  },
  "accelerator": "GPU"
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
