"""build_doc_sections — assemble a complete sections dict for PDF/DOCX rendering."""
from __future__ import annotations

from datetime import datetime
from typing import Dict, List

from src.tools.doctools.split_sections import split_sections


def build_doc_sections(
    answer: str,
    citations: List[Dict],
    title: str,
    patient_context: str = "",
) -> Dict[str, str]:
    """
    Build a complete document sections dict including header, body, citations, and disclaimer.
    Ready to pass to generate_pdf() or generate_docx().
    """
    ts = datetime.now().isoformat()
    sections = split_sections(answer)

    out: Dict[str, str] = {
        "header": f"OpenInsight Clinical Summary\nGenerated: {ts}\nQuery: {title}",
    }

    if patient_context:
        out["patient_context"] = patient_context

    for key, val in sections.items():
        out[key] = val

    lines = []
    for c in citations:
        line = f"  {c.get('claim_id', '')} — {c.get('source_title', '')}"
        if c.get("source_url"):
            line += f". {c['source_url']}"
        lines.append(line)
    out["sources_and_citations"] = "SOURCES AND CITATIONS:\n" + "\n".join(lines)

    out["disclaimer"] = (
        "This report was generated by OpenInsight, an AI-powered clinical decision "
        "support system developed by SentArc Labs. It is intended to support, not "
        "replace, clinical judgment. Verify all drug dosages and guidelines against "
        f"current institutional protocols before prescribing. Generated: {ts}."
    )
    return out
